# Generated by Django 4.1.13 on 2024-01-26 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('username', models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('phone_no', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(6)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('coursel_img', models.URLField()),
                ('card_img', models.URLField()),
                ('category', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('duration', models.CharField(max_length=10)),
                ('star_rating', models.FloatField()),
                ('type_rating', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=50)),
                ('actors', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('in_coursel', models.BooleanField()),
            ],
        ),
    ]
