# Generated by Django 4.1.13 on 2024-02-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemagicapp', '0002_booking_city_theater_seat_booking_city_booking_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
